"""add path to code model

Revision ID: 1bef6d0b57e3
Revises: 8e66633032aa
Create Date: 2018-06-05 20:53:52.039801

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1bef6d0b57e3'
down_revision = '8e66633032aa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('code', sa.Column('code_path', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('code', 'code_path')
    # ### end Alembic commands ###
