"""modify code path to code

Revision ID: 36c1d54fe621
Revises: 5cda12e0f1eb
Create Date: 2018-06-07 16:57:57.969310

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '36c1d54fe621'
down_revision = '5cda12e0f1eb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('submit', sa.Column('code', sa.Text(), nullable=True))
    op.drop_column('submit', 'code_path')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('submit', sa.Column('code_path', mysql.VARCHAR(length=255), nullable=True))
    op.drop_column('submit', 'code')
    # ### end Alembic commands ###
