"""merge code to submit models, fix some

Revision ID: b9f8f6113c39
Revises: 1bef6d0b57e3
Create Date: 2018-06-07 00:18:31.135980

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b9f8f6113c39'
down_revision = '1bef6d0b57e3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('language', sa.Column('compile_command', sa.String(length=200), nullable=True))
    op.add_column('submit', sa.Column('accessable', sa.Integer(), nullable=True))
    op.add_column('submit', sa.Column('byte', sa.Integer(), nullable=True))
    op.add_column('submit', sa.Column('code_path', sa.String(length=255), nullable=True))
    op.drop_constraint('submit_ibfk_1', 'submit', type_='foreignkey')
    op.drop_column('submit', 'code_id')
    op.drop_table('code')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('submit', sa.Column('code_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.create_foreign_key('submit_ibfk_1', 'submit', 'code', ['code_id'], ['id'])
    op.drop_column('submit', 'code_path')
    op.drop_column('submit', 'byte')
    op.drop_column('submit', 'accessable')
    op.drop_column('language', 'compile_command')
    op.create_table('code',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('problem_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('language_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('byte', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('accessable', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('code_path', mysql.VARCHAR(length=255), nullable=True),
    sa.ForeignKeyConstraint(['language_id'], ['language.id'], name='code_ibfk_1'),
    sa.ForeignKeyConstraint(['problem_id'], ['problem.id'], name='code_ibfk_2'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='code_ibfk_3'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
